# Build stage
FROM maven:3.6-jdk-8 as build
WORKDIR /backend
COPY ./pom.xml ./
RUN mvn dependency:go-offline -B
COPY ./ ./
RUN mvn clean package

# Create final image
FROM openjdk:8-jre-alpine
VOLUME /tmp
WORKDIR /backend
COPY --from=build /backend/target/backend-1.0-SNAPSHOT-runner.jar ./
COPY --from=build /backend/target/lib ./lib/
EXPOSE 8080
ENV MONGOCONNSTRING mongodb://localhost:27017
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dquarkus.mongodb.mrt.connection-string=${MONGOCONNSTRING}","-jar","/backend/backend-1.0-SNAPSHOT-runner.jar"]
